apiVersion: v1
kind: PersistentVolume
metadata: 
  name: sos-backend-pv
  labels: 
    name: sos-backend-pv
spec: 
  capacity:   
    storage: 1Gi 
  storageClassName: manual 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: "/home/k8s/test/so-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-master.lexray.local
