apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: sos-backend-pvc
spec: 
  accessModes:    
    - ReadWriteOnce 
  storageClassName: manual 
  resources:   
    requests:     
      storage: 1Gi
